### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by BrewChef** [IndyJoeA/cbpi_ToggleStep#1]
Would it be possible to implement "auto" function and perhaps a "pause" function?

Lets say we start a brewday with HLT-on, BK-off, run trough the mash steps, at the end we turn HLT-off (after mashout) - gets to pause, do lautering and transfer to BK, then continue and BK starts with auto as well?

**Comment by IndyJoeA** [comment]
I think I would prefer the plugin to remain as simple as possible, and not have other features built in.  Things like a pause or wait step could be done as a separate step.  Thanks for the idea though!
